### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by PhilChodrow** [lchen777-cl/D-B-PIC16B-Project#1]
Make sure that your repository includes only **your** code. It looks like some of this might be part of a plotly tutorial? If it's not being directly used, remove it. If you do make use of code that you took from a tutorial or other source, make sure to cite it in your `README.md` and in the corresponding `.py` file. There should be no code in the repository other than what is necessary to make your app run. 

`openpyxl` also appears to be a requirement to run your app. 

After installing this and the other required packages, I encountered an error in the terminal which makes me unable to interact with your app. Because of this, I can't really comment on what more might be appropriate for your app. If, overall, you find that it meets your goals, that it is possible for a user to interact with and learn from it, that you learned something by creating it, and that you're proud of the result, this should be good enough for the project. 

For now, please research the error below and let me know when you'd like me to try again to run your app. 

```
(PIC16B) ~/D/D/D-B-Webapp ❯❯❯ flask run
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 479-108-622
failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces
Traceback (most recent call last):
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
    result = fn(*args, **kwargs)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 399, in _send_payload
    response = self._put(payload, headers)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 358, in _put
    conn.request("PUT", self._endpoint, data, headers)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 512, in flush_queue
    self._retry_upload(self._send_payload, encoded, n_traces)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 373, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7fa580e15df0 state=finished raised ConnectionRefusedError>]
failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces
Traceback (most recent call last):
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
    result = fn(*args, **kwargs)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 399, in _send_payload
    response = self._put(payload, headers)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 358, in _put
    conn.request("PUT", self._endpoint, data, headers)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 512, in flush_queue
    self._retry_upload(self._send_payload, encoded, n_traces)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 373, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7fc198be6ca0 state=finished raised ConnectionRefusedError>]
```

**Comment by lchen777-cl** [comment]
> Make sure that your repository includes only **your** code. It looks like some of this might be part of a plotly tutorial? If it's not being directly used, remove it. If you do make use of code that you took from a tutorial or other source, make sure to cite it in your `README.md` and in the corresponding `.py` file. There should be no code in the repository other than what is necessary to make your app run.
> 
> `openpyxl` also appears to be a requirement to run your app.
> 
> After installing this and the other required packages, I encountered an error in the terminal which makes me unable to interact with your app. Because of this, I can't really comment on what more might be appropriate for your app. If, overall, you find that it meets your goals, that it is possible for a user to interact with and learn from it, that you learned something by creating it, and that you're proud of the result, this should be good enough for the project.
> 
> For now, please research the error below and let me know when you'd like me to try again to run your app.
> 
> ```
> (PIC16B) ~/D/D/D-B-Webapp ❯❯❯ flask run
>  * Environment: development
>  * Debug mode: on
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
>  * Restarting with stat
>  * Debugger is active!
>  * Debugger PIN: 479-108-622
> failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces
> Traceback (most recent call last):
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
>     result = fn(*args, **kwargs)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 399, in _send_payload
>     response = self._put(payload, headers)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 358, in _put
>     conn.request("PUT", self._endpoint, data, headers)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1256, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1302, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1251, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1011, in _send_output
>     self.send(msg)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 951, in send
>     self.connect()
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 922, in connect
>     self.sock = self._create_connection(
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 808, in create_connection
>     raise err
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 796, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 61] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 512, in flush_queue
>     self._retry_upload(self._send_payload, encoded, n_traces)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
>     do = self.iter(retry_state=retry_state)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 373, in iter
>     six.raise_from(retry_exc, fut.exception())
>   File "<string>", line 3, in raise_from
> tenacity.RetryError: RetryError[<Future at 0x7fa580e15df0 state=finished raised ConnectionRefusedError>]
> failed to send traces to Datadog Agent at http://localhost:8126/v0.4/traces
> Traceback (most recent call last):
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
>     result = fn(*args, **kwargs)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 399, in _send_payload
>     response = self._put(payload, headers)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 358, in _put
>     conn.request("PUT", self._endpoint, data, headers)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1256, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1302, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1251, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 1011, in _send_output
>     self.send(msg)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 951, in send
>     self.connect()
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/http/client.py", line 922, in connect
>     self.sock = self._create_connection(
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 808, in create_connection
>     raise err
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/socket.py", line 796, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 61] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/ddtrace/internal/writer.py", line 512, in flush_queue
>     self._retry_upload(self._send_payload, encoded, n_traces)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
>     do = self.iter(retry_state=retry_state)
>   File "/Users/philchodrow/opt/anaconda3/envs/PIC16B/lib/python3.8/site-packages/tenacity/__init__.py", line 373, in iter
>     six.raise_from(retry_exc, fut.exception())
>   File "<string>", line 3, in raise_from
> tenacity.RetryError: RetryError[<Future at 0x7fc198be6ca0 state=finished raised ConnectionRefusedError>]
> ```

Thank you for the feedback! The pythonfalsk_tutorial folder contains important files, including our dash apps. I've already renamed it to address the confusion. We learned how to embed dash to flask from a website and gave credit to the tutorial on our main webpage. I've also included it in the README file. The web app can still run at http://127.0.0.1:5000/ with the Datadog error. We will try to solve the error by the final submission.

**Comment by lchen777-cl** [comment]
Hello Prof. Chodrow, we've already cleared the Datadog error by Wednesday. We've now deployed the web app to heroku at https://eitc-app.herokuapp.com/. Please feel free to provide any suggestions to improve the project since we still have time to work on it before the final submission.
